name: Publish

# Run when a new release is... released
on:
  release:
    types: [published]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ShipExpander --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          token: ${{ secrets.TS_TOKEN }}
          community: lethal-company
          namespace: JBriggs_DEV # the thunderstore 'team' to publish under
          name: ShipExpander # the name of the package
          description: ShipExpander mod
          version: ${{ github.ref_name }} # Use the tag as the package version
          path: './ShipExpander/bin/publish-Release' # Path to ShipExpander project
          repo: thunderstore.io
          categories: | # <-- notice this pipe character
            mods
          #deps: bbepis-BepInExPack-5.4.9
          deps: | # <-- notice this pipe character
            BepInEx-BepInExPack-5.4.21
          
      
      


        