name: Publish DEV

# Run when a new release is... released
on:
  release:
    types: [published]

#on:
#  push:
#  pull_request:
#    branches:
#      - develop-thunderstore-github-actions
#  workflow_dispatch:
  



jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          token: ${{ secrets.TS_DEV_TOKEN }}
          community: lethal-company
          namespace: JBriggs_DEV # the thunderstore 'team' to publish under
          name: ShipExpander # the name of the package
          description: ShipExpander mod
          version: 0.0.1 # Use the tag as the package version
          #version: ${{ github.ref_name }} # Use the tag as the package version
          path: './ShipExpander' # Path to ShipExpander project
          dev: true
          repo: thunderstore.io
          categories: | # <-- notice this pipe character
            mods
          #deps: bbepis-BepInExPack-5.4.9
          deps: BepInEx-BepInExPack-5.4.2100
          
      
      


        