name: Publish DEV

on:
  push:
    branches:
      - develop-thunderstore-github-actions
  workflow_dispatch:


jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ShipExpander --no-restore # Defaults to debug
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create folder for publish#
        shell: pwsh
        run: ./createPublishFolder.ps1 -config Debug
  publish-dev:
    runs-on: ubuntu-latest
    needs: build-dotnet
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          token: ${{ secrets.TS_DEV_TOKEN }}
          community: riskofrain2 # Not a real community in https://thunderstore.dev
          namespace: JBriggs_DEV
          name: ShipExpander # the name of the package
          description: |
            ShipExpander
            This mod will expand the ship size to support more than 4 players better.
          version: v0.${{ github.run_number }}.0 # Use the tag as the package version
          #version: ${{ github.ref_name }} # Use the tag as the package version
          path: './ShipExpander/bin/publish-Debug' # Path to ShipExpander project
          dev: true
          repo: thunderstore.dev
          # > Commented out due to no categories existing for community test
          categories: | # <-- notice this pipe character
            mods
          deps: | # <-- notice this pipe character
            bbepis-BepInExPack-5.4.9
          
      
      


        