name: Test Action

on:
  push:
  pull_request:
    branches:
      - develop-thunderstore-github-actions
  workflow_dispatch:
  


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: pub
        uses: ./
        with:
          namespace: jbriggs.dev
          name: ShipExpander
          dev: true
          token: ${{ secrets.TS_KEY }}
          description: |
            Ship expander mod. Need to add more of a description here
          version: v0.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.dev
          wrap: mods
          website: "https://jbriggs.dev"
          categories: |
            mods
          deps: |
            BepInEx-BepInExPack-5.4.2100
      - run: echo ${{ steps.pub.outputs.url }}
          
      
      

  # publish:
  #   needs: test
  #   if: github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create Release
  #       uses: marvinpinto/action-automatic-releases@latest
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         prelease: false
        


        